### ISSUE TITLE
in `setup()` or in static mode, initial docstrings are not ignored if they have a quote char

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#130]
![image](https://user-images.githubusercontent.com/3694604/185513019-6371a3bd-0a8b-4f09-bb26-25b761d20980.png)
I found this converting the Python mod examples... :)

**Comment by hx2A** [comment]
Interesting. I'm going to guess this is a shortcoming with a regular expression.

Thanks for the bug report! I'll fix this this weekend.

**Comment by hx2A** [comment]
This problem is not limited to static mode or run_sketch; it applies to any docstring in `setup()`.

I have a fix for this. As expected, it was a shortcoming with a regular expression.
