### ISSUE TITLE
PDF and SVG renderers in `size()` require exit_sketch()

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#137]
```python
import py5

def setup():
    py5.size(500, 500, py5.PDF, 'out.pdf')
    py5.rect(50, 50, 100, 100)
    print(py5.__version__)

py5.run_sketch()
```
console:
`0.8.2.dev0 `

file output: A zero-bytes out.pdf file.

```python
import py5

def setup():
    py5.size(500, 500, py5.SVG, 'out.svg')
    py5.rect(50, 50, 100, 100)
    print(py5.__version__)

py5.run_sketch()
```
console:
`0.8.2.dev0 `

file output:
```
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.0//EN'
          'http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd'>
<svg xmlns:xlink="http://www.w3.org/1999/xlink" style="fill-opacity:1; color-rendering:auto; color-interpolation:auto; text-rendering:auto; stroke:black; stroke-linecap:square; stroke-miterlimit:10; shape-rendering:auto; stroke-opacity:1; fill:black; stroke-dasharray:none; font-weight:normal; stroke-width:1; font-family:'Dialog'; font-style:normal; stroke-linejoin:miter; font-size:12px; stroke-dashoffset:0; image-rendering:auto;" width="500" height="500" xmlns="http://www.w3.org/2000/svg"
><!--Generated by the Batik Graphics2D SVG Generator--><defs id="genericDefs"
  /><g
/></svg
>
```

**Comment by hx2A** [comment]
For both of them you need to call `py5.exit_sketch()` for the Sketch to exit and for the output to be written. Is this different from how Processing and Processing.py works?

**Comment by villares** [comment]
> For both of them you need to call `py5.exit_sketch()` for the Sketch to exit and for the output to be written. Is this different from how Processing and Processing.py works?

Hmmm, interesting! I have not found about the need for an "exit call" in the processing.org `size()` reference: 
https://processing.org/reference/size_.html
https://py.processing.org/reference/size.html

But then... there it is in this PDF library page!
![image](https://user-images.githubusercontent.com/3694604/185813273-931a6207-38e6-4ad2-8c9f-9bedd7590ec5.png)

So I suppose it is "works as designed" :)

Suggestion:
- Could we just add this to the `size()` reference page and be done with it?
- I wouldn't want to divert development effort for this but, but would it be hard to have a post-exit clean up routine for cases like this?

**Comment by hx2A** [comment]
The documentation could be more clear about the need for `exit()`. It is mentioned explicitly at the very end:

> Again, exit() is really important when using PDF with size().

We could mention this in py5's `size()` reference page. I'm not sure what you mean by a post exit clean up routine. Post exit is after exit, and there is no longer a need to call `exit_sketch()` then. Do you mean have py5 call exit for you? I don't know if that's a good idea, we'd have to think that through to make sure there are no bad side effects.

**Comment by villares** [comment]
Yeah, precise language can be tricky for describing it... I meant something that could execute after a sketch ends if `exit_sketch()` is not called to guarantee things are closed properly. But I see it could be hard.

I vote to just close this with a mention added to the `size()` page for now.

**Comment by hx2A** [comment]
> I vote to just close this with a mention added to the `size()` page for now.

Yes, I think that's the right thing to do here. Would you like to make a PR for this change?

**Comment by villares** [comment]
Oh... Sorry, could you point me for the n-th time to te instructions for
building/contributing to the docs?

**Comment by hx2A** [comment]
No problem. You need to submit a PR for a change to [this file](https://github.com/py5coding/py5generator/blob/main/py5_docs/Reference/api_en/Sketch_size.txt), adding a sentence or two to the `@@ description` section.

**Comment by hx2A** [comment]
This fixed and I merged the PR. Thank you!
