### ISSUE TITLE
sketch_path() behavior: an easy documentation enhancement? maybe a warning?

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#163]
I have been bitten time and again by Processing's `sketchPath()` method, if you use it before `setup()` it will give you what I suppose are useless results. The method in py5, based on it, works the same.

Demo:
```python
# from  /home/villares/GitHub/python_play_reboot/py5_play/demo.py

data_folder = sketch_path('data') 
print(data_folder)
# /home/villares/miniconda3/envs/py5/lib/python3.8/site-packages/py5/data

def setup():
    size(400, 400)
    data_folder = sketch_path('data') 
    print(data_folder)
# /home/villares/GitHub/python_play_reboot/py5_play/data   
``` 

Docs page: http://py5coding.org/reference/sketch_sketch_path.html

Could we add this information to the documentation page?  Normally I'd like to do it myself but I'm a bit overwhelmed right now.
Could we add a warning if it is called before `setup()`?

PS: How wonderful it is that it returns a `pathlib.Path` object!
PS2: I was reminded of this 'issue' when updating this tutorial about loading all images from a folder: https://github.com/villares/material-aulas/blob/main/Processing-Python-py5/imagens_externas_pasta2.md

**Comment by hx2A** [comment]
> Could we add this information to the documentation page? Normally I'd like to do it myself but I'm a bit overwhelmed right now.
Could we add a warning if it is called before setup()?

We could add a warning, or how about return something relative to `os.getcwd()`? I agree that anything is an improvement over the status quo. Ideally I'd like it to somehow involve `__file__` of the code that made that call to `sketch_path()`, but I don't see a clear way to do that reliably. Actually, I don't like a solution that returns something different before `setup()` vs after, even if what is returned is more useful than `/home/villares/miniconda3/envs/py5/lib/python3.8/site-packages/py5/data`. How about this: what if the Sketch is not running, display a warning, saying that it should be called after `setup()` or you should use `os.getcwd()` instead?

> PS: How wonderful it is that it returns a pathlib.Path object!

My friend, one way or another I'm going to get you to use `pathlib.Path` objects!

**Comment by villares** [comment]
You mean `pathlib.Path.cwd()`?  😆

**Comment by hx2A** [comment]
Haha, that works also!

**Comment by hx2A** [comment]
@villares , this was on Linux?

I just tested this on OSX using Jupyter and the run_sketch util and surprisingly `sketch_path()` returns the same result before and after `setup()`. On OSX, there's no need to change anything.

I'll test this Windows and Linux and will only add a warning to those if it is necessary.

**Comment by villares** [comment]
Yes, I'm on Linux most of the time. I'll see if I can test on Windows too.

**Comment by hx2A** [comment]
This is now fixed. For all platforms, users will see the below message when the method is called for a non-running Sketch:

```txt
/Users/jim/INSTALL/anaconda3/envs/py5/lib/python3.8/site-packages/py5/sketch.py:489: UserWarning: Calling method sketch_path() when Sketch is not running. The returned value will not be correct on all platforms. Consider calling this after setup() or perhaps using the Python standard library methods os.getcwd() or pathlib.Path.cwd().
```

I thought it would be best to direct users to not use sketch_path() in a way that does not work on all platforms, even if it does work correctly on their machine. I don't think it is a good idea to silently allow this and then someone shares their code with someone else and gets confused by different results.
