### ISSUE TITLE
a funny sketch_runner (imported mode) syntax error message edge case?

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#176]
As I accidentally removed the body of a conditional structure at the end of my sketch, the expected syntax error became... another error because of the sketch_runner post-processing :) 

I have no idea how we could deal with this!

![image](https://user-images.githubusercontent.com/3694604/199627942-7101a2d6-1365-4c51-8a36-697a3161fdfe.png)

Some minimal code for reproducing: 

```python
def setup():
    size(200, 200)
    
def draw():
    pass

def key_pressed():
    if key == ' ':
        # missing `if` body at the end of sketch
```

**Comment by hx2A** [comment]
Hmmm, interesting. Your indentation error tripped up Python's ability to find the true location of the indentation error. I looked at the responsible code and it should be relatively easy to fix. Thanks for stumbling onto this bug!

**Comment by hx2A** [comment]
Thanks again for spotting this error, @villares !!
