### ISSUE TITLE
How to deal with `vertices()`, and other functions that expect collections, when arguments provided are empty?

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#195]
According to the Zen o Python, `Errors should never pass silently.\Unless explicitly silenced.`

How could we deal with the errors that occur when passing empty collections to the drawing functions that expect collections?
The `for` loop that it replaces would have been just skipped...

Should we check for empty collections ourselves (look before you jump), use exception handling (feels overkill)?
Should it emit a warning only?  Should we have a a flag that we turn off to silence those errors, like `rect_mode(CENTER)` ?

```python
def draw_elements(element):
    if isinstance(element, (MultiPolygon, GeometryCollection)):
        for p in element.geoms:
            draw_elements(p)
    elif isinstance(element, Polygon):
        with begin_closed_shape():
            #if element.exterior.coords:
                vertices(element.exterior.coords)
                for hole in element.interiors:
                    with begin_contour():
                        vertices(hole.coords) 
```

![image](https://user-images.githubusercontent.com/3694604/203328973-0c3fdeac-6465-48fb-94f7-ed82e4b79ffd.png)

**Comment by claudefalbriard** [comment]
This might help: 
    if element.exterior.coords is not None:

**Comment by hx2A** [comment]
Welcome, @claudefalbriard !

This might be a bug or shortcoming in py5. @villares , can you run that code again using `prune_tracebacks(False)` and then post the exception?

https://py5coding.org/reference/py5functions_prune_tracebacks.html

py5 will remove some of the java stuff and other complexity from stack traces to provide better errors to users. That can be deactivated though. For diagnosing this particular error, some relevant information is being lost.

Normally `list(element.exterior.coords)` gives you a list of lists, ie `[[1, 2], [3, 4], ...]`. When the error takes place, is it `[]` or `[[]]`?

py5 should not be presenting the user with a java exception, so this is a bug of some kind. I think calling `vertices()` with zero vertices should be allowed. Internally the code needs to convert the coordinates to a java array, and it could be that java array has the wrong dimensions and that is what is causing the error.

**Comment by hx2A** [comment]
I just looked at the relevant code and I see the error. This will be fixed in the next release.

**Comment by hx2A** [comment]
Fixed! On a roll today fixing bugs.
