### ISSUE TITLE
py5 class objects should implement `__str__()` and `__repr__()`

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#209]
Why not provide better information than `<py5.sketch.Sketch at 0x7f0d6be806a0>` or `<py5.mouseevent.Py5MouseEvent object at 0x0000018F3E0B96D0>` when these are printed? It's a simple change.

**Comment by shyam-sunder-19** [comment]
This is a great idea, I want to work on this, I believe I will get to know a lot about the codebase along the way.

**Comment by AsadNizami** [comment]
Does the py5generator class has some documentation? I can see a lot of resources for py5, but not for the generator. I am not able to understand how the codebase is being generated here.

**Comment by hx2A** [comment]
> Does the py5generator class has some documentation? I can see a lot of resources for py5, but not for the generator. I am not able to understand how the codebase is being generated here.

The [build process](https://py5coding.org/developer/build_process.html) is documented on the website. I am working on more documentation for how py5 and py5generator works.

For this enhancement, you'd have to go find the classes in this directory:

https://github.com/py5coding/py5generator/tree/main/py5_resources/py5_module/py5

The files are shape.py, shader,py, sketch.py, etc. Find the class definitions and add the str and repr methods to each.

**Comment by hx2A** [comment]
Fixed with #251. Thanks, @AsadNizami !
