### ISSUE TITLE
Python exceptions for Processing mode function calls are not handled properly

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#234]
When should it display a Python stack trace? When should it throw a Java exception? Should the error handling behavior be user specified?

@villares has pointed out that select_folder(), select_file(), etc are very hard to debug. These should not be swallowing exceptions.

**Comment by hx2A** [comment]
@villares, can you provide an example where one of py5's select functions throws an exception in a callback and is hard to debug?

When I test with the below code:

```python
import py5


def f(selection):
    x = 10 / 0
    py5.println(selection)


def setup():
    py5.size(200, 200, py5.P2D)


def mouse_pressed():
    py5.select_input('pick a file any file', f)


def draw():
    py5.rect(py5.mouse_x, py5.mouse_y, 10, 10)


py5.run_sketch()
```
 yields this result:

```txt
% python test.py
py5 encountered an error in your code:File "test.py", line 5, in f
    4    def f(selection):
--> 5        x = 10 / 0
    6        py5.println(selection)

ZeroDivisionError: division by zero
```

**Comment by hx2A** [comment]
If the callback function has the wrong number of parameters there is a proper error message but I think this can be improved with Python's inspect library to validate the callback when the select method is called.

**Comment by villares** [comment]
Hmmm, I could reproduce the silencing in Processing 3.5.4 Python mode (the `pf` function never reaches `print`):
![image](https://user-images.githubusercontent.com/3694604/219966840-9e7cc9f1-6336-4efa-ad55-ef8d49857623.png)

But couldn't reproduce it in py5! 
I even tried a different FileIO related Exception...

```python
import py5

def pf(folder):
    with open('this file does not exist', 'r') as f:
        print(f)
    print(type(folder), folder)

def settings():
    py5.size(100, 100)
    
def key_pressed():
    py5.select_folder('hi', pf)
    
def draw():
    py5.circle(100, 100, py5.frame_count % 100)
    
py5.run_sketch()
```

Maybe something changed in Processing 4's core and I missed it?

Maybe this is a *non-issue* after all?!?

**Comment by hx2A** [comment]
> Maybe something changed in Processing 4's core and I missed it?

Can you reproduce it in java Processing 4?

> Maybe this is a non-issue after all?!?

py5 has its own exception handling that is totally different from what Processing 4 does. In this situation, Processing 4 having a difficulty with callback exception handling will not carry over to py5.

Java and Python each have their own way of handling exceptions and they cannot throw each other's exceptions. py5 needs its own exception handling mechanisms that work for both, cause the Sketch to stop at the appropriate time, and require a Java call to `System.exit(0)` to exit the window (which is what Processing does). Balancing all of these needs was a serious undertaking, and is one of the more complicated aspects of py5.

Separately, I've tested Processing mode exception handling and it seems to work fine. It will show you the Python stack trace and then throw a Java exception, which the user can catch and handle or allow to stop the Sketch as it would for a Java Processing Sketch.

**Comment by villares** [comment]
Python mode doesn't even start for me in Processing 4.
I tried this in Java... looks like something changed, to me:

![image](https://user-images.githubusercontent.com/3694604/219967972-cc0a842d-c342-476d-a3b5-a06096cfa017.png)

**Comment by hx2A** [comment]
> PS: Maybe it is just "broken" in a different way now, because the console doesn't look like a traditional Processing error message 😆

Yes, that's probably it. Managing exception handling for a callback is difficult to code, so I totally understand.

I am going to close this out but add a few things to the other issue related to the select methods.
