### ISSUE TITLE
'int' object is not iterable

### ISSUE THREAD

**Issue by marziabil** [py5coding/py5generator#235]
Hello, 

I am seeing an error here where i have defined bright. The error is TypeError: 'int' object is not iterable:

`def setup():
    py5.size(599, 900)
    global img
    img = py5.load_image("venus.jpg")

def draw():
    py5.background(255, 255, 255)
    tiles = 10
    tileSize = py5.width/tiles
    x = 0
    y = 0
    for x in range(tiles):
        for y in range (tiles):

            c = py5.color(img.get(int(x*tileSize),int(y*tileSize)))
            bright = float(map(py5.brightness(c), 0,255,0,1))

            py5.push()
            py5.translate(x*tileSize, y*tileSize)
            py5.no_stroke()
            py5.fill(0)
            py5.ellipse(0,0, tileSize, tileSize)
            py5.pop()
    
py5.run_sketch()`

I was following this tutorial: [https://www.youtube.com/watch?v=WEBOTRboXBE] and the similar code is at 14:50.

**Comment by hx2A** [comment]
Hello, @marziabil ! Looks like you were able to fix your code before I could respond.

In py5, Processing's `map()` function is called `py5.remap()` to avoid a name conflict with the built-in Python function `map()`. This is also true for `filter()`, which becomes `py5.apply_map()` in py5.

**Comment by marziabil** [comment]
Hi,

Thanks for your reply!

I had a question - slightly different from the above.

The international conference on computational creativity is being held in
June this year. Would you be interested in a possible collaboration to
write a research paper?

I used py5 for my MSc thesis - GitHub.com/marziabil/emojis

Thanks,
Marzia

**Comment by hx2A** [comment]
Wow, how nice that you used py5 for your master's thesis! I am thrilled it served you well for your project.

Looking at your project I realized you emailed me about this once before but I mistakenly did not reply. I do apologize for that. I read through your masters thesis and I see you did a lot of work for that and that you write well. Good job!

I did not know about the [Association for Computational Creativity](https://computationalcreativity.net/) but will learn more about it in the near future. What kind of a paper are you suggesting, and on what topic? Some of these deadlines are in a few days. I have thought about writing something about py5 for Siggraph but don't have the bandwidth for something like that now. Someday it will happen, when I either clone myself or figure out how to work more efficiently!

**Comment by marziabil** [comment]
Ah I felt so happy when I saw your email this morning!

You shouldn't apologize! I am sure you receive quite a lot of emails - I
found your work really interesting and at that point I was jobless so I
reached out to you if I could work with you and learn from you as well to
use my time better.

The deadline for the full paper is quite close, but we can work on a short
paper (deadline in May). The special topics for this year are quite
interesting - Call for short papers
<https://computationalcreativity.net/iccc23/short-papers/>, particularly
the one on Climate change:

   - Climate Change: Climate change is an urgent issue that impacts all of
   us. What role can CC play in tackling this challenge? This year we would
   like to explore the overlap between Computational Creativity and the global
   climate crisis. We welcome submissions on systems that create, or engage in
   the creation of, creative artifacts (visual art, music, poetry, etc) that
   bring awareness to the climate change crisis. Other related research may
   include systems that propose creative solutions to the climate crisis, or
   any other valuable ideas that combine CC and the topic of climate change
   and environmental sustainability.


I have been thinking about this and one of my ideas was something about
neural style transfer - showing the impact of climate change through images
- for instance, a system that shows what the world would look like after 20
or an x number of years - specifically landscapes. I still need to think
more about this such as how I would be able to depict this. For example, if
glaciers are melting, how would the system know that it should apply this
rule for a glacier? I am relatively new to machine learning, unfortunately.

I just googled Siggraph - it seems pretty cool, but unfortunately, the
deadline has passed. I do enjoy writing and making art (both on the
computer and on paper) so if you need assistance with anything do let me
know! Ever since I completed my Master's I have been getting zero
satisfaction from my full-time job and I wish to pursue these interests on
the side (not a lot of work is being done in Pakistan on this either).

This email got a bit long, but I hope to hear from you soon.

Best,
Marzia
