### ISSUE TITLE
Attribute Error suggestions don't work in imported mode

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#276]

**Comment by hx2A** [comment]
Fixed with #277

**Comment by hx2A** [comment]
@villares , this is now fixed.

```txt
% run_sketch test_static_imported.py
py5 encountered an error in your code:


--> 1    c = colour(255, 0, 0)
    2    background(c)

NameError: The name colour is not defined. Did you mean "color"?
```

Works for the py5bot and py5 kernels and the run_sketch command line utility.

**Comment by hx2A** [comment]
@villares I just uploaded the py5 test distribution files to the same place where you got the previous one. Thank you again for your testing and diligence finding bugs.

Also, this is the first GitHub Copilot-assisted code fix. It is not a magic wand but it did help move this long faster.

**Comment by villares** [comment]
Hurray! I have just tested it on Linux and it worked brilliantly.
