### ISSUE TITLE
Remove `g` from py5

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#322]
Currently `py5.g` is deprecated. This issue is a reminder to remove it completely from py5 in a future build.

- [x] remove `g`
- [x] confirm that it is no longer a reserved name for a variable or a function
- [x] update the reference documentation. Should it be removed completely, or add a note saying "as of version X, this has been removed from py5?"

See #317 for prior discussion.

**Comment by villares** [comment]
I like the idea of leaving some message.

**Comment by hx2A** [comment]
> I like the idea of leaving some note about the removal!

OK, that's what I will do.

**Comment by villares** [comment]
This page's example will be affected by the `g` removal: https://py5coding.org/reference/py5graphics_next_page.html

**Comment by hx2A** [comment]
> This page's example will be affected by the `g` removal: https://py5coding.org/reference/py5graphics_next_page.html

Good catch! I just fixed that. There shouldn't be any deprecated code in the documentation.

There are no other similar examples and no links to the `.g` reference doc pages.
