### ISSUE TITLE
`get_pixels()` does not work correctly for Py5Image objects

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#330]
Returns a bare Java object but should return a Py5Image image object instead.

https://github.com/py5coding/py5generator/discussions/328#discussioncomment-6571609

**Comment by villares** [comment]
Cheers @hx2A, when was/will be this fix released?

**Comment by hx2A** [comment]
If it doesn't work I will certainly fix it. What is the problem? I thought
it worked fine.

(I am in Miami still and not in front of my computer)

**Comment by hx2A** [comment]
> I guess the fix is on the next release, and i should be testing the dev ... sorry for that.

No worries! You are correct, this will work correctly in the next release.

And about the next release...still determined to get it done by the end of the year. I'm hoping I can get the documentation 100% done by next weekend, but I'm also bogged down by holiday stuff right now.
