### ISSUE TITLE
Issue on page /reference/py5functions.html

### ISSUE THREAD

**Issue by harrih** [py5coding/py5generator#338]
Hi there just coming to py5 and python
Very happy to stumble across this development as Im  attempting to do some fairly maths intensive work in the processing environment where python libs would be invaluable.

Trying to use with Thonny  in an 86 osx environment
seems to all work with exception of  code completion.
No idea if this is a Py5 or Thonny issue. 

By whatever method I invoke code completion  the cursor stalls just after 
whatever  suggestion  is selected.
  e g     rect ^ (                           
 _^ represents stuck cursor position_
The only response available from keyboard or mouse is to add repeated suggestions   
 "rects" in this case

eg i get     _rectrectrectrectrectrectrectrect ^ (_
only way Ive found to exit this without shutting Thonny
 is to go into options and turn off code completion and that will release the cursor.
makes py5 in Thonny very difficult to use at present

**Comment by hx2A** [comment]
Welcome, @harrih , and thank you for your interest in py5.

@villares , can you provide some insight here? You have more experience using py5 and Thonny.

**Comment by harrih** [comment]
On further investigation seems to be on the Thonny side
H

**Comment by hx2A** [comment]
Thank you, @harrih . I hope you get Thonny working well for your situation. If you figure out a great solution, please let us know what you come up with!

I will close this Issue for now since there isn't a py5 issue for me to work on.
