### ISSUE TITLE
Layout with widgets and sketch_portal unpredictable

### ISSUE THREAD

**Issue by sawula** [py5coding/py5generator#34]
This code can produce the following layouts of widgets and `sketch_portal`.  Not clear how to control the layout.

![image](https://user-images.githubusercontent.com/3756836/127757673-e5e9ca12-15fc-411e-aab1-3b875fd35c03.png)

a)
![image](https://user-images.githubusercontent.com/3756836/127757676-bbbaab51-3e27-4e0b-927e-7053b70c18d4.png)

b)
![image](https://user-images.githubusercontent.com/3756836/127757680-40e0d163-402d-4be2-bf46-58aa5baf28cd.png)

c)
![image](https://user-images.githubusercontent.com/3756836/127757686-5d4d0c39-e6f1-485b-b30e-6acfdec451a8.png)

**Comment by hx2A** [comment]
Have a look at the ipywidgets documentation. The widgets include layout widgets, which are perfect for controlling their arrangement. It happens py5 uses a VBox widget to position the button widget below the Image widget.

https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Container/Layout-widgets

**Comment by hx2A** [comment]
@sawula did that documentation help?

**Comment by hx2A** [comment]
I'm going to close this, because the Layout widgets like HBox and VBox are great for specifying the order of widgets.
