### ISSUE TITLE
The `import py5` command should detect headless Java installations and warn users of the problem

### ISSUE THREAD

**Issue by cuniculus-0** [py5coding/py5generator#346]
On Ubuntu 22.04.3 LTS, withOpenJDK 19 and Python 3.11 (note, cairo is also installed), I am unable to get past this one problem, and not finding any documentation on Processings site:

When running the intro tutorial:

```python
def setup():
    size(400, 400)
    rect_mode(CENTER)


def draw():
    square(mouse_x, mouse_y, 10)


def mouse_clicked():
    fill(random_int(255), random_int(255), random_int(255))


run_sketch()
```

I get:

```bash
Cannot run sketch without a display. Read this for possible solutions:
https://github.com/processing/processing/wiki/Running-without-a-Display
```

**Comment by hx2A** [comment]
Hmmm, interesting problem, @cuniculus-0 ! What happens when you type echo $DISPLAY in a terminal?

How are you attempting to run that code? Is the code in a file and you are running it from the terminal with a command like this: `run_sketch test.py`?

Can you try installing the Processing PDE and see if you can run a test sketch there?

**Comment by cuniculus-0** [comment]
Hi @hx2A , thanks for the quick response.

I'm running this snippet as a Python file.

`> python test.py`

But also tried the mentioned `run_sketch test.py` with same result.

My `$DISPLAY` is set to `:0.0` so not sure if the problem lies there?

When running PDE I have no problems, `JAVA_HOME` is also set. jpype seams fine when running `jpype.startJVM()`

When running this in Jupyter Lab, the kernel simply keeps crashing, with both `py5` and `py5bot` kernels.

Also, I was trying all of this in virtual envs, thought it might have something to do with that, so I installed on my local installation, (thus no venv), same result. Luckily, I guess, as it would suck to not be able to run py5 in a virtual env.

How can I help debugging this issue?

**Comment by hx2A** [comment]
Hi @cuniculus-0 . Can you try running the example code but in module mode? The methods should each have the `py5.` prefix. Then execute it with `python test.py` in the command line.

There seems to be something odd about your machine. It doesn't have access to a frame buffer like it should. Any chance this is Windows Subsystem Linux or running in a virtual machine?

**Comment by cuniculus-0** [comment]
I tried in module mode, same result.

Also, running this works fine:

```python
import py5_tools

# this will be False
print(py5_tools.is_jvm_running())

import py5

# now it will be True
print(py5_tools.is_jvm_running())
```

Running this on installed Linux, no subsystem or VM.

**Comment by hx2A** [comment]
@cuniculus-0 , can you try adding this to the beginning of the Python file?

```
import os

print('display', os.environ['DISPLAY'])
```

I am on my phone, there might be some typos there. The goal is to see what Python sees as the `DISPLAY` environment variable.

**Comment by hx2A** [comment]
@cuniculus-0 , I'm going to guess your Java JRE is a headless JRE and not a full JRE. How did you install Java 19? I believe you can search for the installed packages with `sudo apt list "*java*"`. If the word "headless" appears in the Java 19 package, you might be able to fix this by installing a different, non-headless JRE.

**Comment by cuniculus-0** [comment]
Success!
I was sure that I installed the no-headless JRE, but turns out it was the culprit.
Not sure how that happened, but uninstalling the headless one and installing the other 1.19 worked, 
thanks, and sorry for the trouble. I should have double checked. 

Keep up the great work!

**Comment by hx2A** [comment]
@cuniculus-0 , totally fine, no trouble at all. This is actually an opportunity to improve py5. At a minimum, the installation documentation should explicitly state that headless Java installations should not work, and in addition, it seems [it is possible for py5 to detect if it is using a headless JRE](https://stackoverflow.com/questions/16610525/how-to-determine-if-graphicsenvironment-exists/16611566#16611566). If this works, I can have py5 output a suitable error message on the `import py5` command to let the user know they have a headless JRE and need to fix that. That's more instructive than the error message you got about no display.

I'm going to reopen this and change the title to reflect this helpful feature.

**Comment by hx2A** [comment]
OK! I just tested this new safety feature to inform users if they are using a headless JVM.

```
>>> import py5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jim/INSTALL/anaconda3/envs/py5/lib/python3.8/site-packages/py5/__init__.py", line 78, in <module>
    raise RuntimeError(
RuntimeError: py5 is unable to run correctly in headless mode. Make sure you are running in a graphical environment and that your Java Virtual Machine is not a Headless JVM.
```

This throws an exception and will not let the user continue. Thank you, @cuniculus-0 , for opening this issue; now, nobody else will get tripped up by a headless JVM.

**Comment by hx2A** [comment]
I also added additional information to the install instructions in a few places making it clear that a headless jvm will not work.

http://dev.py5coding.org/content/install.html
