### ISSUE TITLE
Enhancement: Add precise frame control to `py5_tool.animated_gif`

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#350]
The `py5_tool.animated_gif` feature is great, but I miss from the _gifAnimation_ library that I used with Processing Java/Python mode the "fine control" of choosing to add frames in some circumstances...

```python
from py5_tools import animated_gif

n = 10

def setup():
    size(500, 500)
    no_stroke()
    frame_rate(16)
    # filename, number of frames, sample interval, frame duration in gif
    animated_gif('test.gif', n, 0.05, 1)
        
def draw():
    background(100)
    fill(255)
    text_size(40)
    text(frame_count, 200, 200)
    
    
    if frame_count > n + 5:
        exit_sketch()
```
![test](https://github.com/py5coding/py5generator/assets/3694604/92432361-b851-45fc-a2f5-8f5e68e03fc6)

When making small loops the "time control" afforded by `animated_gif` doesn't seem helpful. I then usually export all frames (or every odd frame) and generate the animation elsewhere. Am I missing somethig? 

A lazy idea... could we have `animated_gif_from_frames(filename, list_of_frames, duration)`?

_Originally posted by @villares in https://github.com/py5coding/py5generator/discussions/349_

**Comment by hx2A** [comment]
I started working on this and basically have it working.

I also should add this feature to `py5_tools.capture_frames()`. It shares code with the animated gif feature so I might as well include it.

https://py5coding.org/reference/py5tools_capture_frames.html

The function signatures of both will change a bit as a result.

**Comment by hx2A** [comment]
@villares , here's what the new functions look like:

http://dev.py5coding.org/reference/py5tools_capture_frames.html
http://dev.py5coding.org/reference/py5tools_animated_gif.html

This is a breaking change because some of the parameters are now keyword only.

**Comment by villares** [comment]
Great!

Check out this example, please: https://github.com/py5coding/py5examples/blob/main/notebooks/Simple%20py5%20Examples.ipynb

I'm going to hunt my sketch-a-day sketches that use `animated_gif`.

**Comment by hx2A** [comment]
> Great!
> 
> Check out this example, please: https://github.com/py5coding/py5examples/blob/main/notebooks/Simple%20py5%20Examples.ipynb

After this release, that example won't work. The first parameter is fine but the last three will need to be keyword arguments:

```python
py5_tools.animated_gif('images/test.gif', count=10, period=1, duration=1)
```

**Comment by villares** [comment]
Yeah, this is what I was thinking, "retrofitting" my previous sketches with keyword arguments.

**Comment by villares** [comment]
I hate regex, but I think this worked fine. I used *regexxer*, a helper to find and replace stuff on multiple files, for those less well versed with the traditional CLI regex workflow.

![image](https://github.com/py5coding/py5generator/assets/3694604/2f237aba-1adc-4a9c-b887-9091b9d10015)

**Comment by hx2A** [comment]
> I hate regex, but I think this worked fine. I used _regexxer_, a helper to find and replace stuff on multiple files, for those less well versed with the traditional CLI regex workflow.

Good choice!

Nobody likes regex at first. The only way to learn to like regex is to use it frequently enough that you get good at it. I try to seek out opportunities to use regex so I can continue build my ability to use regex.
