### ISSUE TITLE
`save_frame()` cannot be called from a mouse or keyboard event function but that works fine in Processing

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#394]
From @villares:

> About this, being careful of what you do outside the animation thread, I was very surprised today to learn that I can't call py5.save_frame(...) from my key_pressed() event function when using P3D (an OpenGL renderer)! Was that always so? Or is is it something new to Processing 4? Also I would say it is not intuitive to think of saving an image as a "drawing method"...

Here's what's happening:

py5's `save_frame()` is different from Processing's `saveFrame()`. py5 uses the PIL image library to save the image, letting you save the image in many formats and all the other nice features PIL has. py5 also lets you save to a `BytesIO` object. For these work, it needs to access the frame's pixels, calling Processing's `updatePixels()` method. That call must be triggering that error.

The error message should be improved, and if possible, the functionality should be repaired. Ideally this would work.

The `save_frame()` method can tell if it is being called from `draw()` or not. Then it can fall back to Processing's method instead, or perhaps use `py5_tools.screenshot()`.

What about `save()`? Should test that also.

_Originally posted by @hx2A in https://github.com/py5coding/py5generator/discussions/355#discussioncomment-7960774_

**Comment by villares** [comment]
My naive solution would be something like this (pseudocode):
```
if legacy_mode:
    legacy_save(...)
else:
    try:
        pillow_save(...)
    except TroubleSaving: 
        warning('Use legacy_mode=True when outside draw()!')
        legacy_save(...)
 ```

**Comment by hx2A** [comment]
> My naive solution would be something like this (pseudocode):

The issue in py5 isn't the saving, its the getting the pixels that will be saved to the image. Processing's `save()` method takes care of this. When saving with PIL, py5 needs to get the pixels from `load_pixels()` first.

I thought of a better solution than what is above; py5 can save with Processing's `saveFrame()` if the user wants to save in a format that Processing can handle. If not it will use PIL, getting the pixels from `load_pixels()` first.

**Comment by hx2A** [comment]
+PR #415 for this issue

Fixed! Now py5 will use Processing's `save()` method when it can't call `load_pixels()`. If the user wants to save the image in a format Processing supports it will do so directly. If not, it will save to a temporary PNG file, load it back, and then save it again with PIL.
