### ISSUE TITLE
Issue on page /integrations/colors.html

### ISSUE THREAD

**Issue by 6OmpH9** [py5coding/py5generator#395]
After reading the page I wanted to experiment with the Colour library integration.
- I installed the colour library with pip
- I copied all the code including the from colour import Color

When I run in vscode I get this error:
- TypeError: The parameter types (Color) are invalid for method fill.

But I read this in the article so I'm quite confused:
- "The colour library is integrated into py5. Any method with color parameters that accepts Hex Color Codes or Hexadecimal Integers will also accept instances of the colour.Color class."
- "In our example, we were able to create instances of colour.Color and pass them to the fill() method."

I'm not 100% sure if this is an issue or my own error, I tried looking around to solve the problem on my own but I couldn't.
Thanks.

**Comment by hx2A** [comment]
> Issue on page /integrations/colors.html

Wait, first, can you tell me how you got to that page? It seems like you found your way onto the dev website http://dev.py5coding.org/integrations/colors.html. The production website, py5coding.org, doesn't have that page. If I have a link somewhere leading you to that page, I need to fix that ASAP.

> After reading the page I wanted to experiment with the Colour library integration.

Thank you for your enthusiasm for trying new features, @6OmpH9 !

There will be a py5 release tomorrow, and after the release goes out, this feature will work for you. I'm trying to get everything ready for the release. Please be patient, this takes time!

**Comment by 6OmpH9** [comment]
Oh that makes sense then, I was actually confused about how I found my way there too.

I was looking around for some inspiration for a py5 sketch and I found this conversation which mentioned some new tutorials. https://github.com/py5coding/py5generator/discussions/205

thanks to you in the team for the doing the work. I'm looking forward to the new release!

**Comment by hx2A** [comment]
> I was looking around for some inspiration for a py5 sketch and I found this conversation which mentioned some new tutorials. #205

Great! You can find those completed tutorials here:

https://py5coding.org/tutorials/intro_to_py5_and_python.html

> thanks to you in the team for the doing the work. I'm looking forward to the new release!

You are welcome! I appreciate it.

If you want to be inspired by what you'll be able to do with py5 after this weekend, have a look at what's new:

http://dev.py5coding.org/integrations/python_ecosystem_integrations.html

I'm going to close this issue because there is nothing to fix. Thanks again for your interest in py5!

**Comment by hx2A** [comment]
@6OmpH9 the new release is live!
