### ISSUE TITLE
Tarea Vocabulario inicial de dibujo de py5

### ISSUE THREAD

**Issue by miguerangel** [py5coding/py5generator#427]
Cuando introduzco el  codigo y lo ejecuto el  comando en Thonny, el reproductor desaparece inmediatamente y no puedo observar lo que he generado.
<
def setup():
    size(980,980)
    background(200, 0, 0 )
    rect_mode(CENTER)
    fill(0, 200, 0)
    stroke(255, 0, 0)
    stroke_weight(5)
    rect(width / 2, height / 2, 200,50)
    no_stroke()
    fill(255)
    ellipse(200 ,200, 300, 100)
    >
![2 1](https://github.com/py5coding/py5generator/assets/162797022/420e14eb-760b-4470-81ef-ad552a0e8fb3)

**Comment by hx2A** [comment]
I adore the fact that we have a global community that opens issues in languages other than English.

I can use Google translate to understand what is being said here. I recall an earlier version of py5 had this problem. My first suggestion is to check the py5 version and make sure the latest version is installed. @villares , can you assist @miguerangel here to provide guidance?

**Comment by villares** [comment]
¡ Saludos @miguerangel !
No hablo muy bien español así que estoy usando la traducción automática, espero que funcione...

Jim (@hx2A) sugiere que verifique la versión de py5 para que podamos investigar si se trata de un regreso de un problema que teníamos antes.

Para hacer esto, puede escribir las siguientes líneas en la parte inferior de Thonny (presione ENTER/RETURN después de cada una), el `>>>` no lo escribe, es el indicador de la consola:

```python
>>> importar py5
>>> py5.__versión__
```
El resultado debería ser algo así : 
![image](https://github.com/py5coding/py5generator/assets/3694604/d9c5a027-d9d6-4b76-ad14-7e17e9ab89b0)

Algunos de mis alumnos tuvieron este problema.
y lo solucionaron añadiendo una función extra (que no debería ser necesaria):

```python
def draw():
    pass
```

Esto no es realmente una solución, es un esquema de emergencia que puedes usar para continuar con tus dibujos.

**Comment by miguerangel** [comment]
"Bom dia, muito obrigado pela resposta tão rápida. Funciona, eu uso o ChatGPT para a tradução e acho que funciona bem.”
Un saludo. Miguel Ángel.

**Comment by villares** [comment]
Saludos, Miguel!
¿Está todo funcionando?
¿Podemos cerrar esta "issue" abierta?

**Comment by miguerangel** [comment]
Buenos días, Sí, muchísimas gracias por el interés.
Miguel Ángel.
