### ISSUE TITLE
javaaccessbridge.dll error

### ISSUE THREAD

**Issue by robotita** [py5coding/py5generator#459]
Hello, when I try to run the code in Thonny, I get the following error:

_Java exception thrown by Sketch.runSketch:
java.lang.UnsatisfiedLinkError: C:\Users\autoa\AppData\Roaming\Thonny\jdk-17\bin\javaaccessbridge.dll: Can't find dependent libraries_

Why could this error be happening? 
Thank you very much in advance.

**Comment by hx2A** [comment]
Hi, @robotita !

Can you check your computer and see if that dll file exists in that directory?

I am guessing this has something to do with your JDK install. Can you tell us how you setup Thonny with py5? It could be the JAVA_HOME environment variable is not set correctly.

@villares , have you seen this error before?

**Comment by villares** [comment]
> @villares , have you seen this error before?

Someone at my Domestika coures mentioned it, I "saw it" today for the first time! it could have been @robotita, maybe?
I'll keep an eye on this.

**Comment by robotita** [comment]
Thank you for the prompt response ! : )
Yes, the dll exists and the JAVA_HOME path seems to be correct (I also tried routing it to my Java folder but it gives me the same error).

![java_home](https://github.com/py5coding/py5generator/assets/12633316/0ee69c1d-6386-4e54-b289-4e6a4b5bfa89)
![dll_path](https://github.com/py5coding/py5generator/assets/12633316/9849b443-883b-43e2-a17d-9626f7b18a1f)

**Comment by villares** [comment]
I'm so sorry you are having this trouble.

May I ask, is this a "pre-configured portable Thonny with py5 in a zip" I recommend on my instructions? Or have you installed a fresh Thonny IDE from Thonny.org and then installed py5 and then the py5 thonny-py5mode plug-in?

Could you test the "other" option?

**Comment by robotita** [comment]
Yes, it happens on both, it's probably something with my operating system, right? 
Thanks a lot for your response.
I'll keep trying to see if I manage to get it to work : )

![portable](https://github.com/py5coding/py5generator/assets/12633316/db83c24d-2f74-4305-8f50-66804bcefd2d)

**Comment by hx2A** [comment]
@robotita , you got it to work?

**Comment by robotita** [comment]
@hx2A 
yesss ✧⁺⸜(  •‿•  )⸝⁺✧
I tried so many things that I'm not sure what worked, but I deleted all the versions of Java I had and reinstalled Java (I suppose that was it) and also installed py5.
thanks for all!

**Comment by hx2A** [comment]
@robotita , your persistence paid off. Good job!
