### ISSUE TITLE
Py5Shape's `get_children()` method should return `[]` when there are no children

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#501]
Both for empty `GROUP` shapes and non-`GROUP` shapes.

**Comment by hx2A** [comment]
From discussion #500

**Comment by hx2A** [comment]
@villares , can you provide some example code that reproduces this bug?

I believe this is an easy fix, but when I was testing my fix, I realized my test code could not reproduce the problem when I didn't include my code change.

**Comment by villares** [comment]
The shapely experiment I posted (without an if guard) sometimes produced this I think (like when overlapping all circles). I'm away from the computer, but I'll try to remember providing some other shorter code to reproduce this!

**Comment by hx2A** [comment]
> The shapely experiment I posted (without an if guard) sometimes produced this I think (like when overlapping all circles). I'm away from the computer, but I'll try to remember providing some other shorter code to reproduce this!

I thought of that, and already tried to reproduce it with that code. Then I realized I could try sometime simple:

```python
def setup():
    s = py5.create_shape()
    print(s.get_children())
```

That did reproduced it. I'll merge the fix now.

**Comment by villares** [comment]
Ha! This is exactly what I wrote when I got back to the computer! Cool!
