### ISSUE TITLE
Provide a way to disable the `ESC` key behavior of quiting a sketch

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#549]
It should be possible to set `py5.key` to something other than ESC, allowing the user to skip quitting a Sketch.

### Discussed in https://github.com/py5coding/py5generator/discussions/548

Just need to make the `key` property settable.

**Comment by hx2A** [comment]
I sat down to fix this because I felt like closing an easy issue today but discovered this one is not an easy fix. Or the approach I propose in the discussion is not at all easy. It would be possible to make `key` settable by the user in class mode but it is harder for module mode and quite messy or impossible for imported mode. There's some magic behind how the dynamic variables work with in imported mode that includes some AST transformations. The magic and the AST transformations would be upset if I tried to make `key` user changeable. Theoretically it might be possible but it would require a lot of complicated code for just one thing.

Let me think about other options. There could be a `set_key()` method but seems ugly to me. What if there was an `intercept_exit()` method you could call instead of needing `key = ' '`?

**Comment by villares** [comment]
Yes, I think the important thing is to be able to disable the quitting behavior, like, avoid closing the sketch in order to use the ESC key.

It might be even better as a feature, more "discoverable" if we have a method!

I was thinking, could that also intercept the windows closing action? Would that be useful?

**Comment by hx2A** [comment]
> Yes, I think the important thing is to be able to disable the quitting behavior, like, avoid closing the sketch in order to use the ESC key.
> 
> It might be even better as a feature, more "discoverable" if we have a method!

OK, I'll see how feasible an `intercept_exit()` method is.

> I was thinking, could that also intercept the windows closing action? Would that be useful?

You mean the exit button in the corner? That's a different can of worms, separate from the ESC key. I don't think it is a good idea to mess with that.

**Comment by hx2A** [comment]
> OK, I'll see how feasible an `intercept_exit()` method is.

I just looked at the code and it looks feasible.

**Comment by hx2A** [comment]
I created a new method called `intercept_escape()`, which I thought was more precise than `intercept_exit()`. Here's the documentation:

http://dev.py5coding.org/reference/sketch_intercept_escape.html
