### ISSUE TITLE
Possible improvements to the exploratory/experimental translator tools

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#68]
The `py5_tools` module contains some great tools to help convert code made for Processing Python Mode (Py.Processing) into code that works with py5, and between py5 imported mode and py5 module mode. 

One can never expect the translations to be 100% perfect, as an infinite number of contextual things can go wrong, specially libraries and other Processing + Jython environmental peculiarities. It is provided as a time saving "experimental" feature.

This issue could try and document ideas for improvements in the translation tools.

### From py5 imported to py5 module
- `from random import choice, randint` or `import random` or `import random as rnd` should not bring in `py5.random`
     Possible solution: skip import lines?   `from math import sin` becomes `from math import py5.sin` that doesn't help either.
     This would need  some line context, the [`translate_code()`](https://github.com/villares/py5generator/blob/9cc2aa37291c22ee2c7b2454a35145455c2ce555/py5_resources/py5_module/py5_tools/translators/util.py#L27) function has limited line context (mostly previous tokens). 
     Could I try to add a flag for `from` and `import` maybe? 

```python
    out = StringIO()
    in_comment = False
    in_quote = None
    in_import_line = False
    for token in tokens:
        if token in ("'", '"""', '"', "'''") and not in_comment:
            if not in_quote:
                in_quote = token
            elif in_quote and token == in_quote:
                in_quote = None
        elif token in ('import', 'from'):
            in_import_line = True
        elif token == '#':
            in_comment = True
        elif token == '\n':
            in_comment = False
            in_import_line = False
        elif not (in_comment or in_quote or in_import_line):
            token = translate_token(token)

        out.write(token)
```
>  EDITED on 2022-08-01 to reflect PR I created

A `from` flag would be dangerous because of the `yield from generator` construction. Maybe search lines after conversion and undo import lines...

- if token in ["'", '"'] and not in_comment:
   can I change this to this?
   `if token in ["'", '"""', '"', "'''"] and not in_comment:`

**Comment by hx2A** [comment]
Thank you for opening this discussion.

> One can never expect the translations to be 100% perfect, as an infinite number of contextual things can go wrong, specially libraries and other Processing + Jython environmental peculiarities. It is provided as a time saving "experimental" feature.

Right, exactly. The goal here is not to provide perfect translations. The goal is to save time by doing most of the tedious and mechanical work.

> This issue could try and document ideas for improvements in the translation tools.

One idea that comes to mind after reading the points you made is to try using the `ast` library. Abstract Syntax Trees are already used to make imported mode work, whether that be in the py5 kernel or the run_sketch util. An AST would be able to separate the context of the keyword "random" in `random(2, 3)` from its use in `from random import choice`.

BTW, py5 already has the math and random functions you are using, so you don't need to import from the math or random standard libraries.

* http://py5.ixora.io/reference/sketch_random_choice.html
* http://py5.ixora.io/reference/sketch_random_int.html
* http://py5.ixora.io/reference/sketch_random.html
* http://py5.ixora.io/reference/sketch_sin.html

However, there's nothing wrong with using `from math import sin` or even `from numpy import sin`. Both are valid code. But, there's no way for py5's translator to know if `sin(x)` refers to py5's `sin()` or a similarly named function from numpy or math. Abstract syntax trees will solve the problem of not breaking the import statement with `from math import py5.sin` but will always convert `sin(x)` to `py5.sin(x)`. The abstract syntax tree can only know that a function named `sin` is being called. Which one is actually called can only be determined at runtime.

**Comment by villares** [comment]
I have played with the standard library `tokenize` module and I was surprised it was not what you were using. Now I feel like diving in `ast` would be overkill right now. 

I see exactly your point, my idea was kind of 'least change approach'. just skipping the import lines, mainly because changing them creates code that doesn't run.

Keeping the `py5.sin()` & etc even after `from math import sin`, will still run and maybe the person using the translator will find about the `py5.sin` they didn't know it before. The manual decision could be just to delete the unneeded import line.

**Comment by hx2A** [comment]
I started with `tokenize` but found it didn't add value over the current approach, and it seemed to cause some headaches with whitespace. The `ast` stuff is more challenging but I now know more about how to use it for this purpose.

**Comment by villares** [comment]
I think we can close this, and if any other ideas emerge we can start at discussions, or open another issue!
