### ISSUE TITLE
save() and save_frame() can make it easy to set an image's ALT text

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#85]
Use what @villares figured out to set an image's metadata, which becomes an image's ALT text in twitter.

https://twitter.com/villares/status/1530998628759871489

Q: would this approach work on other platforms? Is this the most widely supported approach of doing this?

**Comment by villares** [comment]
Ops! I'm not sure it becomes an ALT text on twitter! 
I couldn't reproduce this...
Maybe what you saw was an ALT I added manually?

**Comment by hx2A** [comment]
Oh no! I didn't realize you added the alt text manually. Did I just promise something on Twitter that isn't possible?

**Comment by hx2A** [comment]
Just did some Googling and it seems meta data alt text isn't a thing. I'm disappointed it isn't. Wouldn't it be more accessible if content creators could add this to their images, and it would stay with the image?

**Comment by villares** [comment]
It would be really cool!

**Comment by hx2A** [comment]
I'm going to close this, but will keep an eye out for ideas I can use to make py5 more accessible.
