### ISSUE TITLE
[MacOS Apple Silicon] Error when closing the window

### ISSUE THREAD

**Issue by nicolasmelo1** [py5coding/py5generator#87]
Hello,

So i've came from the @villares thread on twitter asking to test the library on Apple Silicon. 

Everything worked fine (also the py5.2D and py5.3D) except when closing the py5 window at certain moments.

## Tools used

- Macbook Pro M1 16GB RAM
- Python 3.9.13
- openjdk 18.0.1.1

## Error image
![Captura de Tela 2022-06-07 às 11 39 06](https://user-images.githubusercontent.com/12915742/172418251-ebeb500e-01c5-432b-852f-58cc40a49027.png)

## Steps to reproduce

As i said on Twitter, the error appears between runs, the first time i run it doesn't show any error. When i run again the error appears (it doesn't matter if i stop the program either by clicking the window (x) or the by hitting ctrl+c on the terminal, the error will always appear)

**Comment by hx2A** [comment]
@nicolasmelo1 Thanks again for testing this and for opening an issue. This is an easy fix and will be resolved in the next release.

**Comment by hx2A** [comment]
This exception will go away after the next release. Thanks!
