### ISSUE TITLE
Feature request: create a new method analogous to Processing's hex() function

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#97]
@tabreturn @marcovicci 

What do you think of this for a hex function? It can convert Processing's funny color integer values into something more readable. The output is a string that looks like `'#FFFF0000'`.

This works slightly different from Processing's [hex](https://processing.org/reference/hex_.html) function in that the string has a '#' at the front. I think this is better because it can then be used as a parameter to other py5 methods `fill()`, `stroke()`, etc that accept color arguments.

```python
    @classmethod
    def to_hex_color(cls, color: int) -> str:
        return '#' + hex(np.uint32(color & 0xFFFFFFFF))[2:].zfill(8).upper()
```

I think `to_hex_color` is a better name than `to_hex` because this emphasizes that this is intended to be used for py5's colors and is limited to 8 hex digits. This contrasts with Python's builtin `hex()` function, which has no limit. 

I told you half the work would be picking a name for it. ;)

**Comment by hx2A** [comment]
This done. The below is now valid py5 code:

```python
def setup():
    c = py5.color(15, 63, 240)
    hex_c = py5.hex_color(c)
    py5.text_size(20)
    py5.fill(hex_c)
    py5.text(hex_c, 2, 55)
```
I dropped the `to_` from the name to be consistent with other py5 methods, such as `degrees()` or `radians()`. There are no py5 methods or functions that start with `to_*`.

The variable `hex_c` above is an 8 character hex color string which as you can see can now be used as a color value to `py5.fill()`. This expands the color hex string functionality you @tabreturn  asked for quite a while ago. Previously the color hex strings could only be 3 or 6 characters long.

In addition, while working on this feature, I found and fixed a bug related to the matplotlib color feature I added a month ago.

**Comment by tabreturn** [comment]
Great work, @hx2A -- agreed, `hex_color()` seems like the most appropriate name.
