### ISSUE TITLE
Processing's selectInput() or selectFolder(), etc

### ISSUE THREAD

**Issue by hx2A** [py5coding/py5generator#98]
Can I add Processing's selectInput() or selectFolder(), etc. to py5's API? If not, what can py5 offer users who are looking for this functionality?

[From this discussion thread](https://github.com/py5coding/py5generator/discussions/96)

**Comment by hx2A** [comment]
I have a working prototype for `py5.select_folder()` that enables py5 to use Processing's `selectFolder()` functionality. It works, but there are two problems:

* The dialog box won't open when run through Jupyter Notebook on OSX. It works just fine with the regular Python interpreter or via Thonny though. I might be able to solve this using what I've learned about these kinds of OSX problems in the past. If I can't, I'll add it to the list of [OSX notes](http://py5.ixora.io/content/osx_users.html).
* This is probably an edge case, but right now the callback mechanism will only allow one select call at a time. It looks like Processing would allow such a thing. I have an idea for how to fix this. I'd rather fix it than allow a user to get caught in a weird situation.

I'm hoping to do a release next week, and if I do, this probably won't be complete in time. I'll be sure to get it in the following release though.

**Comment by hx2A** [comment]
I have `selectFolder()` basically working and will get `selectInput()` and `selectOutput()` working next. I will duplicate what I did for `selectFolder()` for the other two.

The select dialog box doesn't work when run through Jupyter Notebook on OSX. This looks like a limitation we will have to live with. For folks using Jupyter, there are at least ipython widgets one can use instead. The select dialog box works great with the regular Python interpreter and Thonny.

> This is probably an edge case, but right now the callback mechanism will only allow one select call at a time

There was an easy fix for this.

**Comment by hx2A** [comment]
This feature now works and has been tested on all platforms. Two things to note:

* For P2D or P3D Sketches on Windows, the Sketch window will be minimized when the select dialog box is open. This is kind of weird but it is something Windows users will have to live with.
* Native dialog boxes only work on OSX. Windows and Linux use Java's select dialog boxes. Should we make OSX also use non-native dialog boxes to be consistent? I'm fine with letting OSX users have native dialog boxes. Perhaps it will make up for OSX users not being able to use the select functionality when running the Sketch through Jupyter Notebook.

I'll make sure the documentation mentions all of these things.

The last thing I need to deal with is error handling. Right now exceptions display a python and a Java stack trace, and I want to avoid Java stack traces as much as possible.

**Comment by hx2A** [comment]
I now have the error handling the way I like it & the documentation changes are done.

@villares , if you think all of the above looks good to you, I'll merge this.

I have a few minor bugs to take care of and then I'll do a release.

**Comment by villares** [comment]
Looks great!

**Comment by hx2A** [comment]
This is now complete!
